### ISSUE TITLE
No such file or directory: './data/navier_stokes/w_data.mat'

### ISSUE THREAD

**Issue by vasiliyeskin** [stnamjef/SPINN#1]
At the test run for the navier_stokes3d error occurs about unavailable data.

Run is:
CUDA_VISIBLE_DEVICES=0 python navier_stokes3d.py --data_dir=./data/navier_stokes --model=spinn --equation=navier_stokes3d --nt=32 --nxy=256 --seed=111 --lr=0.002 --epochs=100000 --mlp=modified_mlp --n_layers=3 --features=128 --r=128 --out_dim=2 --pos_enc=5 --offset_num=8 --offset_iter=100 --marching_steps=10 --log_iter=1000 --plot_iter=10000

Error:
Traceback (most recent call last):
  File "/content/spinn/navier_stokes3d.py", line 150, in <module>
    train_data = generate_train_data(args, subkey, result_dir=result_dir)
  File "/content/spinn/utils/data_generators.py", line 440, in generate_train_data
    data = _spinn_train_generator_navier_stokes3d(
  File "/content/spinn/utils/data_generators.py", line 310, in _spinn_train_generator_navier_stokes3d
    gt_data = scipy.io.loadmat(os.path.join(data_dir, 'w_data.mat'))
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: './data/navier_stokes/w_data.mat'

**Comment by jwcho5576** [comment]
Sorry for the inconvenience.

We uploaded the data for 2D navier-stokes and diffusion experiment.

Thank you.

**Comment by vasiliyeskin** [comment]
Thank you very much
